export const rooms = [
  {
    id: 1,
    slug: "golden-horizon-retreat",
    name: "Golden Horizon Retreat",
    type: "Double",
    persons: "2 Persons",
    maxGuests: 2,
    price: 130,
    img: "/15.jpeg",
    desc: "Experience elegance and comfort in every detail. Our rooms and suites are thoughtfully designed with...",
    gallery: [
      "/14.jpeg",
      "/13.jpeg",
      "/12.jpeg",
      "/11.jpeg",
    ],
    fullDesc: "Experience elegance and comfort in every detail. Our rooms and suites are thoughtfully designed with modern amenities, creating a perfect blend of style and functionality. Relax in serene surroundings, enjoy personalized service, and indulge in spaces crafted for both leisure and productivity. Whether traveling for business, romance, or a peaceful escape, every stay promises convenience, luxury, and a memorable experience tailored to your needs.",
    includes: [
      "40-inch Samsung® LED TV",
      "Air-conditioning and heating",
      "Rooms equipped with high speed Wifi",
      "Daily maid service",
      "Separate bathtub and rain shower",
      "Express check-in/check-out",
      "24 hour room service",
    ],
    includes2: [
      "Safe electronic room key",
      "Free breakfast starting at 5:30am - 9:00am",
      "Maximum occupancy: 2",
      "Hubway bicycles located directly out door",
      "Separate bathtub and rain shower",
      "Telephone support 24/7",
      "Concierge service",
    ],
    features: [
      { icon: "🍽️", title: "Meeting Rooms", desc: "Turning your wanderlust dreams" },
      { icon: "🏥", title: "First Aid", desc: "Turning your wanderlust dreams" },
      { icon: "🛎️", title: "Reception", desc: "Turning your wanderlust dreams" },
      { icon: "🧹", title: "Cleaning", desc: "Turning your wanderlust dreams" },
      { icon: "📠", title: "Fax Service", desc: "Turning your wanderlust dreams" },
      { icon: "💇", title: "Hair Dryer", desc: "Turning your wanderlust dreams" },
    ],
    amenities: [
      { title: "Comfortable Bed & Pillows", icon: "🛏️" },
      { title: "Fireplace For Atmosphere", icon: "🔥" },
      { title: "Smart TV with Streaming", icon: "📺" },
      { title: "Towels and Washcloths", icon: "🧺" },
      { title: "Video Game Console", icon: "🎮" },
      { title: "Whirlpool Tub For Relaxation", icon: "🛁" },
    ],
    services: [
      { title: "Swimming Pool", img: "https://safar.devsvibe.co/wp-content/uploads/2025/10/accommodation-services-5.png" },
      { title: "Air Conditioned", img: "https://safar.devsvibe.co/wp-content/uploads/2025/10/accommodation-services-4.png" },
      { title: "Meeting Rooms", img: "https://safar.devsvibe.co/wp-content/uploads/2025/10/accommodation-services-6.png" },
      { title: "Under Protection", img: "https://safar.devsvibe.co/wp-content/uploads/2025/10/accommodation-services-3.png" },
      { title: "Free Internet", img: "https://safar.devsvibe.co/wp-content/uploads/2025/10/accommodation-services-2.png" },
      { title: "Laundry Services", img: "https://safar.devsvibe.co/wp-content/uploads/2025/10/accommodation-services-1.png" },
    ],
    details: {
      guests: 2,
      view: "Street View",
      size: "480ft²",
      bedType: "Double",
      category: "Royal Class",
      bedrooms: 1,
      bathrooms: 1,
      location: "French Quarter, New Orleans",
      amenitiesList: "Comfortable Bed & Pillows, Fireplace For Atmosphere, Smart TV with Streaming, Towels and Washcloths, Video Game Console, Whirlpool Tub For Relaxation",
    },
    rating: { overall: 4.6, total: 3 },
    ratingBreakdown: [
      { label: "AMENITIES", value: 4.0 },
      { label: "ENVIRONMENT", value: 4.7 },
      { label: "LOCATIONS", value: 5.0 },
      { label: "PRICE", value: 5.0 },
      { label: "ROOMS", value: 4.7 },
      { label: "SERVICES", value: 4.3 },
    ],
    reviews: [
      { name: "Luca Moretti", date: "November 12, 2025", rating: 5, text: "Safar made hotel booking so effortless! The design is clean, user-friendly, and fast. I found great deals within minutes — highly recommended!" },
      { name: "willowhreek", date: "November 12, 2025", rating: 4.5, text: "I've stayed at many hotels, but Safar stands above the rest. The views, food, and service were phenomenal—definitely deserving of five stars!" },
      { name: "stonehaven", date: "November 12, 2025", rating: 4.33, text: "Perfect getaway at Safar! Peaceful surroundings, tasty food, and clean, modern rooms. Would book again in a heartbeat!" },
    ],
    tags: ["Business Class", "Royal Class", "Standard Class", "Classic", "Economy", "Premium", "100 Eco Friendly", "24/7 Elevator Services", "24/7 Strong Security"],
    lat: 51.5165,
    lng: -0.1509,
  },
  {
    id: 2,
    slug: "serenity-grand-hotel",
    name: "Serenity Grand Hotel",
    type: "Single",
    persons: "2 Persons",
    maxGuests: 2,
    price: 280,
    img: "/14.jpeg",
    desc: "Our thoughtfully designed rooms, world-class amenities, and exceptional service make high-end comfort accessible. Whether you're...",
    gallery: [
      "/11.jpeg",
      "/12.jpeg",
      "/9.jpeg",
      "/10.jpeg",
    ],
    fullDesc: "Our thoughtfully designed rooms, world-class amenities, and exceptional service make high-end comfort accessible. Whether you're here for a quick business trip or an extended holiday, Serenity Grand Hotel offers an unparalleled experience that combines luxury with warmth. Enjoy sweeping views, meticulously curated interiors, and personalized service that anticipates your every need.",
    includes: ["King-size bed with premium linen", "Rainfall shower & soaking tub", "Mini bar & espresso machine", "Smart room controls", "High-speed fiber WiFi", "Pillow menu", "Nightly turndown service"],
    includes2: ["24/7 concierge", "Complimentary breakfast", "Airport transfer option", "In-room safe", "Blackout curtains", "Evening chocolates", "Newspaper delivery"],
    features: [
      { icon: "🍳", title: "Restaurant", desc: "Farm-to-table dining" },
      { icon: "💆", title: "Spa Access", desc: "Full wellness retreat" },
      { icon: "🏋️", title: "Fitness Center", desc: "State of the art gym" },
      { icon: "🏊", title: "Rooftop Pool", desc: "Infinity skyline pool" },
      { icon: "🚗", title: "Valet Parking", desc: "Complimentary valet" },
      { icon: "🧖", title: "Beauty Salon", desc: "In-house treatments" },
    ],
    amenities: [
      { title: "King Bed with Memory Foam", icon: "🛏️" },
      { title: "Private Balcony", icon: "🌅" },
      { title: "Smart TV 55-inch", icon: "📺" },
      { title: "Marble Bathroom", icon: "🛁" },
      { title: "Nespresso Machine", icon: "☕" },
      { title: "In-room Yoga Mat", icon: "🧘" },
    ],
    services: [
      { title: "Rooftop Pool", img: "https://safar.devsvibe.co/wp-content/uploads/2025/10/accommodation-services-5.png" },
      { title: "Spa & Wellness", img: "https://safar.devsvibe.co/wp-content/uploads/2025/10/accommodation-services-4.png" },
      { title: "Fine Dining", img: "https://safar.devsvibe.co/wp-content/uploads/2025/10/accommodation-services-6.png" },
      { title: "Business Center", img: "https://safar.devsvibe.co/wp-content/uploads/2025/10/accommodation-services-3.png" },
      { title: "Free WiFi", img: "https://safar.devsvibe.co/wp-content/uploads/2025/10/accommodation-services-2.png" },
      { title: "Concierge", img: "https://safar.devsvibe.co/wp-content/uploads/2025/10/accommodation-services-1.png" },
    ],
    details: { guests: 2, view: "City View", size: "620ft²", bedType: "Single King", category: "Business Class", bedrooms: 1, bathrooms: 2, location: "Midtown, New York" },
    rating: { overall: 4.8, total: 5 },
    ratingBreakdown: [
      { label: "AMENITIES", value: 5.0 },
      { label: "ENVIRONMENT", value: 4.8 },
      { label: "LOCATIONS", value: 4.9 },
      { label: "PRICE", value: 4.5 },
      { label: "ROOMS", value: 5.0 },
      { label: "SERVICES", value: 4.7 },
    ],
    reviews: [
      { name: "Emma Clarke", date: "December 5, 2025", rating: 5, text: "Absolute perfection! The staff went above and beyond to make our anniversary unforgettable. Would stay again in a heartbeat." },
      { name: "James Wu", date: "December 8, 2025", rating: 4.5, text: "Outstanding service and beautiful rooms. The rooftop pool at sunset was breathtaking." },
    ],
    tags: ["Business Class", "Luxury", "City View", "Premium", "Couples", "Spa"],
    lat: 40.7549, lng: -73.9840,
  },
  {
    id: 3,
    slug: "the-velvet-orchid",
    name: "The Velvet Orchid",
    type: "Single",
    persons: "1 Person",
    maxGuests: 1,
    price: 150,
    img: "/13.jpeg",
    desc: "From luxurious bedding and stylish interiors to personalized service and serene surroundings, every detail is...",
    gallery: [
      "/13.jpeg",
      "/11.jpeg",
      "/9.jpeg",
      "/15.jpeg",
    ],
    fullDesc: "From luxurious bedding and stylish interiors to personalized service and serene surroundings, every detail is curated for your perfect stay. The Velvet Orchid is an intimate boutique experience designed for the discerning solo traveler. Immerse yourself in art, culture, and tranquility within our thoughtfully appointed spaces.",
    includes: ["Queen bed with Egyptian cotton", "Walk-in rainfall shower", "Curated art collection", "Premium sound system", "High-speed WiFi", "Complimentary minibar", "Evening wellness kit"],
    includes2: ["Daily newspaper", "Yoga session access", "Artisan breakfast basket", "Personalized itinerary service", "Pillow menu", "Blackout shades", "24hr room service"],
    features: [
      { icon: "🎨", title: "Art Gallery", desc: "Curated local artwork" },
      { icon: "📚", title: "Library Lounge", desc: "Quiet reading retreat" },
      { icon: "🍵", title: "Tea Ceremony", desc: "Daily wellness ritual" },
      { icon: "🧘", title: "Yoga Studio", desc: "Morning flow classes" },
      { icon: "🌿", title: "Garden Terrace", desc: "Botanical sanctuary" },
      { icon: "🎵", title: "Live Music", desc: "Evening performances" },
    ],
    amenities: [
      { title: "Botanical Sleep Kit", icon: "🌿" },
      { title: "Record Player & Vinyl", icon: "🎵" },
      { title: "Smart TV 4K", icon: "📺" },
      { title: "Freestanding Bathtub", icon: "🛁" },
      { title: "French Press Coffee", icon: "☕" },
      { title: "Handcrafted Minibar", icon: "🍸" },
    ],
    services: [
      { title: "Rooftop Garden", img: "https://safar.devsvibe.co/wp-content/uploads/2025/10/accommodation-services-5.png" },
      { title: "Wellness Studio", img: "https://safar.devsvibe.co/wp-content/uploads/2025/10/accommodation-services-4.png" },
      { title: "Bistro & Bar", img: "https://safar.devsvibe.co/wp-content/uploads/2025/10/accommodation-services-6.png" },
      { title: "24hr Security", img: "https://safar.devsvibe.co/wp-content/uploads/2025/10/accommodation-services-3.png" },
      { title: "Free WiFi", img: "https://safar.devsvibe.co/wp-content/uploads/2025/10/accommodation-services-2.png" },
      { title: "Valet Service", img: "https://safar.devsvibe.co/wp-content/uploads/2025/10/accommodation-services-1.png" },
    ],
    details: { guests: 1, view: "Garden View", size: "380ft²", bedType: "Single Queen", category: "Standard Class", bedrooms: 1, bathrooms: 1, location: "Arts District, Los Angeles" },
    rating: { overall: 4.4, total: 2 },
    ratingBreakdown: [
      { label: "AMENITIES", value: 4.5 },
      { label: "ENVIRONMENT", value: 4.8 },
      { label: "LOCATIONS", value: 4.0 },
      { label: "PRICE", value: 4.5 },
      { label: "ROOMS", value: 4.5 },
      { label: "SERVICES", value: 4.0 },
    ],
    reviews: [
      { name: "Sofia Reyes", date: "January 3, 2026", rating: 4.5, text: "Incredible boutique experience. The art throughout the hotel made every corner a discovery. Truly one-of-a-kind." },
    ],
    tags: ["Solo Travel", "Boutique", "Arts District", "Wellness", "Eco-friendly"],
    lat: 34.0449, lng: -118.2607,
  },
  {
    id: 4,
    slug: "royal-horizon-suites",
    name: "Royal Horizon Suites",
    type: "Triple",
    persons: "3 Persons",
    maxGuests: 3,
    price: 160,
    img: "/11.jpeg",
    desc: "Experience comfort and style at Royal Horizon Suites, where every detail is designed to make...",
    gallery: [
      "/11.jpeg",
      "/9.jpeg",
      "/15.jpeg",
      "/14.jpeg",
    ],
    fullDesc: "Experience comfort and style at Royal Horizon Suites, where every detail is designed to make your stay exceptional. Spacious triple suites offer the perfect setting for families or small groups traveling together. With panoramic views, premium furnishings, and a dedicated suite butler, Royal Horizon delivers a regal experience at every hour.",
    includes: ["Three separate sleeping areas", "Two full bathrooms", "Living room with fireplace", "Dining area for 4", "Full kitchen facilities", "Panoramic view terrace", "Daily chef-prepared breakfast"],
    includes2: ["Suite butler service", "Kids welcome amenities", "Board games & entertainment", "Premium streaming services", "In-suite laundry", "Grocery pre-stocking", "Airport limousine service"],
    features: [
      { icon: "👑", title: "Royal Butler", desc: "24hr personal butler" },
      { icon: "🍕", title: "Private Chef", desc: "In-suite dining" },
      { icon: "🎠", title: "Kids Club", desc: "Supervised activities" },
      { icon: "🏊", title: "Private Pool", desc: "Suite-exclusive pool" },
      { icon: "🚁", title: "Helipad Access", desc: "Scenic flight option" },
      { icon: "🎭", title: "Event Space", desc: "Private celebrations" },
    ],
    amenities: [
      { title: "Royal King Beds x3", icon: "🛏️" },
      { title: "Private Terrace", icon: "🌄" },
      { title: "Home Theater System", icon: "🎬" },
      { title: "Double Jacuzzi", icon: "🛁" },
      { title: "Wine Cellar Access", icon: "🍷" },
      { title: "Premium Game Console", icon: "🎮" },
    ],
    services: [
      { title: "Private Pool", img: "https://safar.devsvibe.co/wp-content/uploads/2025/10/accommodation-services-5.png" },
      { title: "Kids Club", img: "https://safar.devsvibe.co/wp-content/uploads/2025/10/accommodation-services-4.png" },
      { title: "Fine Dining", img: "https://safar.devsvibe.co/wp-content/uploads/2025/10/accommodation-services-6.png" },
      { title: "Security & Safety", img: "https://safar.devsvibe.co/wp-content/uploads/2025/10/accommodation-services-3.png" },
      { title: "Business Center", img: "https://safar.devsvibe.co/wp-content/uploads/2025/10/accommodation-services-2.png" },
      { title: "Valet & Concierge", img: "https://safar.devsvibe.co/wp-content/uploads/2025/10/accommodation-services-1.png" },
    ],
    details: { guests: 3, view: "Mountain & Sea", size: "1200ft²", bedType: "Triple King", category: "Royal Class", bedrooms: 3, bathrooms: 2, location: "Monaco Riviera" },
    rating: { overall: 4.9, total: 7 },
    ratingBreakdown: [
      { label: "AMENITIES", value: 5.0 },
      { label: "ENVIRONMENT", value: 5.0 },
      { label: "LOCATIONS", value: 4.8 },
      { label: "PRICE", value: 4.7 },
      { label: "ROOMS", value: 5.0 },
      { label: "SERVICES", value: 4.9 },
    ],
    reviews: [
      { name: "The Hassan Family", date: "February 10, 2026", rating: 5, text: "Best family suite we've ever stayed in. The kids loved the club, and we adored the private pool. Absolutely regal!" },
      { name: "Marco & Friends", date: "February 14, 2026", rating: 4.8, text: "Celebrated our group anniversary here — the butler arranged everything perfectly. Exceptional in every way." },
    ],
    tags: ["Royal Class", "Family", "Group Travel", "Luxury Suite", "Private Pool", "Butler Service"],
    lat: 43.7384, lng: 7.4246,
  },
  {
    id: 5,
    slug: "the-heritage-charm",
    name: "The Heritage Charm",
    type: "Single",
    persons: "2 Persons",
    maxGuests: 2,
    price: 220,
    img: "/9.jpeg",
    desc: "Whether you're planning a family trip, a romantic escape, or a business journey, our seamless...",
    gallery: [
      "/9.jpeg",
      "/15.jpeg",
      "/14.jpeg",
      "https://safar.devsvibe.co/wp-content/uploads/2025/10/accommodation-post-2.jpg",
    ],
    fullDesc: "Whether you're planning a family trip, a romantic escape, or a business journey, our seamless blend of heritage charm and contemporary luxury ensures an unforgettable experience. The Heritage Charm hotel is housed in a beautifully restored Victorian building, where original architectural details meet thoughtfully updated interiors.",
    includes: ["Four-poster bed", "Claw-foot soaking tub", "Antique writing desk", "Fireplace", "High-speed WiFi", "Complimentary afternoon tea", "Turndown service with chocolates"],
    includes2: ["Heritage library access", "Morning newspaper", "Complimentary sherry", "Guided historic tour", "Pillow menu", "Parking included", "Bicycle hire"],
    features: [
      { icon: "🏛️", title: "Historic Tours", desc: "Guided heritage walks" },
      { icon: "📖", title: "Reading Room", desc: "Victorian library" },
      { icon: "🍸", title: "Whisky Bar", desc: "Rare single malts" },
      { icon: "🌸", title: "Garden Tea", desc: "Afternoon tradition" },
      { icon: "🎻", title: "Music Room", desc: "Grand piano evenings" },
      { icon: "🕰️", title: "Antique Tours", desc: "In-hotel collection" },
    ],
    amenities: [
      { title: "Victorian Four-Poster Bed", icon: "🛏️" },
      { title: "Period Claw-Foot Tub", icon: "🛁" },
      { title: "Working Fireplace", icon: "🔥" },
      { title: "Original Artwork", icon: "🎨" },
      { title: "Vintage Record Player", icon: "🎵" },
      { title: "Heritage Minibar", icon: "🍷" },
    ],
    services: [
      { title: "Heritage Garden", img: "https://safar.devsvibe.co/wp-content/uploads/2025/10/accommodation-services-5.png" },
      { title: "Library & Lounge", img: "https://safar.devsvibe.co/wp-content/uploads/2025/10/accommodation-services-4.png" },
      { title: "Fine Dining", img: "https://safar.devsvibe.co/wp-content/uploads/2025/10/accommodation-services-6.png" },
      { title: "24hr Security", img: "https://safar.devsvibe.co/wp-content/uploads/2025/10/accommodation-services-3.png" },
      { title: "Free WiFi", img: "https://safar.devsvibe.co/wp-content/uploads/2025/10/accommodation-services-2.png" },
      { title: "Laundry & Press", img: "https://safar.devsvibe.co/wp-content/uploads/2025/10/accommodation-services-1.png" },
    ],
    details: { guests: 2, view: "Garden View", size: "520ft²", bedType: "Single Queen", category: "Standard Class", bedrooms: 1, bathrooms: 1, location: "Kensington, London" },
    rating: { overall: 4.5, total: 4 },
    ratingBreakdown: [
      { label: "AMENITIES", value: 4.5 },
      { label: "ENVIRONMENT", value: 4.8 },
      { label: "LOCATIONS", value: 4.5 },
      { label: "PRICE", value: 4.2 },
      { label: "ROOMS", value: 4.6 },
      { label: "SERVICES", value: 4.4 },
    ],
    reviews: [
      { name: "Charlotte B.", date: "March 1, 2026", rating: 5, text: "Stepping into The Heritage Charm was like traveling back in time — in the most wonderful way. Every detail was perfect." },
      { name: "David & Priya", date: "March 5, 2026", rating: 4, text: "Charming property with incredible character. The afternoon tea in the garden was a highlight." },
    ],
    tags: ["Heritage", "Victorian", "Romantic", "London", "Garden", "Classic"],
    lat: 51.5014, lng: -0.1419,
  },
  {
    id: 6,
    slug: "whispering-pines-resort",
    name: "Whispering Pines Resort",
    type: "Double",
    persons: "2 Persons",
    maxGuests: 2,
    price: 175,
    img: "/15.jpeg",
    desc: "Reserve today and step into a world where hospitality meets unforgettable experiences. Every detail is...",
    gallery: [
      "/15.jpeg",
      "/14.jpeg",
      "https://safar.devsvibe.co/wp-content/uploads/2025/10/accommodation-post-2.jpg",
      "/13.jpeg",
    ],
    fullDesc: "Reserve today and step into a world where hospitality meets unforgettable experiences. Every detail is crafted at Whispering Pines Resort to immerse you in the beauty of nature without sacrificing modern comforts. Towering pines, crisp mountain air, and the gentle sound of a nearby creek accompany your stay in our lovingly appointed forest cabins and suites.",
    includes: ["Log-burning fireplace", "Forest-view deck", "Heated flooring", "Cloud 9 mattress", "WiFi throughout", "Daily continental breakfast", "Guided nature walk"],
    includes2: ["Evening s'mores kit", "Stargazing telescope", "Mountain bikes", "Fishing gear rental", "Campfire access", "Pet-friendly rooms available", "Park shuttle"],
    features: [
      { icon: "🌲", title: "Forest Trails", desc: "Guided hiking tours" },
      { icon: "🎣", title: "Fly Fishing", desc: "Creek-side angling" },
      { icon: "🏔️", title: "Mountain Views", desc: "Panoramic outlooks" },
      { icon: "🔭", title: "Stargazing", desc: "Dark sky certified" },
      { icon: "🚵", title: "Mountain Biking", desc: "Trail network" },
      { icon: "🛶", title: "Canoe & Kayak", desc: "Lake adventures" },
    ],
    amenities: [
      { title: "Log-Burning Fireplace", icon: "🔥" },
      { title: "Forest View Deck", icon: "🌲" },
      { title: "Hammock & Swing", icon: "🌅" },
      { title: "Deep Soaking Tub", icon: "🛁" },
      { title: "Bluetooth Speaker", icon: "🎵" },
      { title: "Outdoor Hot Tub", icon: "♨️" },
    ],
    services: [
      { title: "Outdoor Pool & Hot Tub", img: "https://safar.devsvibe.co/wp-content/uploads/2025/10/accommodation-services-5.png" },
      { title: "Nature Activities", img: "https://safar.devsvibe.co/wp-content/uploads/2025/10/accommodation-services-4.png" },
      { title: "Rustic Restaurant", img: "https://safar.devsvibe.co/wp-content/uploads/2025/10/accommodation-services-6.png" },
      { title: "24hr Security", img: "https://safar.devsvibe.co/wp-content/uploads/2025/10/accommodation-services-3.png" },
      { title: "Free WiFi", img: "https://safar.devsvibe.co/wp-content/uploads/2025/10/accommodation-services-2.png" },
      { title: "Laundry Services", img: "https://safar.devsvibe.co/wp-content/uploads/2025/10/accommodation-services-1.png" },
    ],
    details: { guests: 2, view: "Forest & Mountain", size: "560ft²", bedType: "Double Queen", category: "Standard Class", bedrooms: 1, bathrooms: 1, location: "Lake Tahoe, California" },
    rating: { overall: 4.7, total: 6 },
    ratingBreakdown: [
      { label: "AMENITIES", value: 4.8 },
      { label: "ENVIRONMENT", value: 5.0 },
      { label: "LOCATIONS", value: 4.9 },
      { label: "PRICE", value: 4.5 },
      { label: "ROOMS", value: 4.7 },
      { label: "SERVICES", value: 4.5 },
    ],
    reviews: [
      { name: "Tyler & Sam", date: "February 20, 2026", rating: 5, text: "The most peaceful weekend we've ever had. Waking up to pine trees and birdsong, with a fireplace to curl up by — pure bliss." },
      { name: "Outdoor Adventures Blog", date: "March 10, 2026", rating: 4.5, text: "Whispering Pines nails the nature-retreat concept. Activities are excellent and the staff is warm and knowledgeable." },
    ],
    tags: ["Nature", "Mountain", "Forest", "Pet-Friendly", "Couples", "Adventure"],
    lat: 39.0968, lng: -120.0324,
  },
];