export const rooms = [
  {
    id: 1,
    slug: "deluxe-double-room",
    name: "Deluxe Double Room",
    type: "Double",
    persons: "2 Persons",
    maxGuests: 2,
    price: 2300,
    img: "/15.jpeg",
    desc: "Spacious 20m² room with 2 single beds, balcony, garden view, pool view and mountain view. Free toiletries, clothes rack and dining area included.",
    gallery: [
      "/14.jpeg",
      "/13.jpeg",
      "/12.jpeg",
      "/11.jpeg",
    ],
    fullDesc: "Spacious 20m² room with 2 single beds, balcony, garden view, pool view and mountain view. Free toiletries, clothes rack and dining area included. Enjoy flexible booking with free cancellation before 17 May 2026, no prepayment needed — pay at the property, and no credit card needed. Only 4 rooms left — book now to secure your stay.",
    includes: [
      "2 single beds (extra long, > 2 metres)",
      "Free toiletries",
      "Clothes rack",
      "Dining area",
      "Balcony",
      "Garden view",
      "Pool view",
    ],
    includes2: [
      "Mountain view",
      "Free WiFi in public areas",
      "Free private parking on site (reservation needed)",
      "Accessible parking",
      "Coffee machine",
      "Tea/Coffee maker",
      "Breakfast in the room",
    ],
    features: [
      { icon: "🍽️", title: "Restaurant", desc: "On-site dining available" },
      { icon: "🏥", title: "First Aid", desc: "Safety deposit box on site" },
      { icon: "🛎️", title: "Reception", desc: "24-hour front desk" },
      { icon: "🧹", title: "Cleaning", desc: "Daily housekeeping" },
      { icon: "📠", title: "Concierge", desc: "Concierge & tour desk" },
      { icon: "💇", title: "Express Check-in", desc: "Express check-in/check-out" },
    ],
    amenities: [
      { title: "Extra Long Beds (> 2 metres)", icon: "🛏️" },
      { title: "Outdoor Fireplace", icon: "🔥" },
      { title: "Private Bathroom", icon: "🛁" },
      { title: "Free Toiletries", icon: "🧴" },
      { title: "Balcony", icon: "🌅" },
      { title: "Coffee Machine", icon: "☕" },
    ],
    services: [
      { title: "Outdoor Swimming Pool", img: "https://safar.devsvibe.co/wp-content/uploads/2025/10/accommodation-services-5.png" },
      { title: "Air Conditioning", img: "https://safar.devsvibe.co/wp-content/uploads/2025/10/accommodation-services-4.png" },
      { title: "Meeting Rooms", img: "https://safar.devsvibe.co/wp-content/uploads/2025/10/accommodation-services-6.png" },
      { title: "24hr Security", img: "https://safar.devsvibe.co/wp-content/uploads/2025/10/accommodation-services-3.png" },
      { title: "Free WiFi", img: "https://safar.devsvibe.co/wp-content/uploads/2025/10/accommodation-services-2.png" },
      { title: "Laundry Services", img: "https://safar.devsvibe.co/wp-content/uploads/2025/10/accommodation-services-1.png" },
    ],
    details: {
      guests: 2,
      view: "Garden / Pool / Mountain View",
      size: "20m²",
      bedType: "2 Single Beds",
      category: "Deluxe",
      bedrooms: 1,
      bathrooms: 1,
      location: "On-site",
      amenitiesList: "Extra Long Beds, Private Bathroom, Free Toiletries, Balcony, Coffee Machine, Clothes Rack, Dining Area",
    },
    rating: { overall: 4.6, total: 3 },
    ratingBreakdown: [
      { label: "AMENITIES", value: 4.0 },
      { label: "ENVIRONMENT", value: 4.7 },
      { label: "LOCATIONS", value: 5.0 },
      { label: "PRICE", value: 5.0 },
      { label: "ROOMS", value: 4.7 },
      { label: "SERVICES", value: 4.3 },
    ],
    reviews: [
      { name: "Luca Moretti", date: "November 12, 2025", rating: 5, text: "Safar made hotel booking so effortless! The design is clean, user-friendly, and fast. I found great deals within minutes — highly recommended!" },
      { name: "willowhreek", date: "November 12, 2025", rating: 4.5, text: "I've stayed at many hotels, but Safar stands above the rest. The views, food, and service were phenomenal — definitely deserving of five stars!" },
      { name: "stonehaven", date: "November 12, 2025", rating: 4.33, text: "Perfect getaway at Safar! Peaceful surroundings, tasty food, and clean, modern rooms. Would book again in a heartbeat!" },
    ],
    tags: ["Deluxe", "Double Room", "Balcony", "Garden View", "Pool View", "Mountain View", "Free Cancellation", "No Prepayment", "Family Friendly"],
    lat: 51.5165,
    lng: -0.1509,
  },
  {
    id: 2,
    slug: "standard-king-room",
    name: "Standard King Room",
    type: "Single",
    persons: "2 Persons",
    maxGuests: 2,
    price: 2800,
    img: "/14.jpeg",
    desc: "Comfortable Standard King Room with 1 single bed, city view, free WiFi, and flexible booking options including free cancellation.",
    gallery: [
      "/11.jpeg",
      "/12.jpeg",
      "/9.jpeg",
      "/10.jpeg",
    ],
    fullDesc: "Comfortable Standard King Room with 1 single bed, city view, free WiFi, and flexible booking options. Enjoy free cancellation before 17 May 2026, no prepayment needed — pay at the property, and no credit card needed. Breakfast included option available at ₹2,800 per night. A great value stay with full access to all property facilities.",
    includes: [
      "1 single bed (extra long, > 2 metres)",
      "Private bathroom",
      "Free toiletries",
      "City view",
      "Free WiFi",
      "Air conditioning",
      "Tea/Coffee maker",
    ],
    includes2: [
      "Free private parking (reservation needed)",
      "Accessible parking",
      "Daily housekeeping",
      "24-hour front desk",
      "Concierge service",
      "Express check-in/check-out",
      "Room service",
    ],
    features: [
      { icon: "🍳", title: "Restaurant", desc: "On-site restaurant" },
      { icon: "💆", title: "Evening Entertainment", desc: "Evening entertainment & staff" },
      { icon: "🏋️", title: "Outdoor Pool", desc: "Free outdoor swimming pool" },
      { icon: "🏊", title: "Water Slide", desc: "Pool open all year, all ages" },
      { icon: "🚗", title: "Free Parking", desc: "Free private parking on site" },
      { icon: "🧖", title: "Family Friendly", desc: "Indoor play area & kids' meals" },
    ],
    amenities: [
      { title: "Extra Long Bed (> 2 metres)", icon: "🛏️" },
      { title: "City View", icon: "🌆" },
      { title: "Tea/Coffee Maker", icon: "☕" },
      { title: "Private Bathroom", icon: "🛁" },
      { title: "Air Conditioning", icon: "❄️" },
      { title: "Safety Deposit Box", icon: "🔒" },
    ],
    services: [
      { title: "Outdoor Swimming Pool", img: "https://safar.devsvibe.co/wp-content/uploads/2025/10/accommodation-services-5.png" },
      { title: "Spa & Wellness", img: "https://safar.devsvibe.co/wp-content/uploads/2025/10/accommodation-services-4.png" },
      { title: "Fine Dining", img: "https://safar.devsvibe.co/wp-content/uploads/2025/10/accommodation-services-6.png" },
      { title: "Business Center", img: "https://safar.devsvibe.co/wp-content/uploads/2025/10/accommodation-services-3.png" },
      { title: "Free WiFi", img: "https://safar.devsvibe.co/wp-content/uploads/2025/10/accommodation-services-2.png" },
      { title: "Concierge", img: "https://safar.devsvibe.co/wp-content/uploads/2025/10/accommodation-services-1.png" },
    ],
    details: { guests: 2, view: "City View", size: "20m²", bedType: "1 Single Bed", category: "Standard", bedrooms: 1, bathrooms: 1, location: "On-site" },
    rating: { overall: 4.8, total: 5 },
    ratingBreakdown: [
      { label: "AMENITIES", value: 5.0 },
      { label: "ENVIRONMENT", value: 4.8 },
      { label: "LOCATIONS", value: 4.9 },
      { label: "PRICE", value: 4.5 },
      { label: "ROOMS", value: 5.0 },
      { label: "SERVICES", value: 4.7 },
    ],
    reviews: [
      { name: "Emma Clarke", date: "December 5, 2025", rating: 5, text: "Absolute perfection! The staff went above and beyond to make our anniversary unforgettable. Would stay again in a heartbeat." },
      { name: "James Wu", date: "December 8, 2025", rating: 4.5, text: "Outstanding service and beautiful rooms. The rooftop pool at sunset was breathtaking." },
    ],
    tags: ["Standard", "King Room", "Free Cancellation", "No Prepayment", "Free Parking", "Outdoor Pool", "Family Friendly"],
    lat: 40.7549, lng: -73.9840,
  },
  {
    id: 3,
    slug: "deluxe-double-room-half-board",
    name: "Deluxe Double Room — Half Board",
    type: "Double",
    persons: "2 Persons",
    maxGuests: 2,
    price: 3300,
    img: "/13.jpeg",
    desc: "All the comforts of the Deluxe Double Room with breakfast & lunch included. Free cancellation before 17 May 2026, no prepayment or credit card needed.",
    gallery: [
      "/13.jpeg",
      "/11.jpeg",
      "/9.jpeg",
      "/15.jpeg",
    ],
    fullDesc: "Enjoy all the comforts of the Deluxe Double Room with the added benefit of breakfast & lunch included (Half Board). Free cancellation before 17 May 2026, no prepayment needed — pay at the property, and no credit card required. The room features 2 single beds, a balcony with garden, pool and mountain views, and 20m² of stylish space. Only 4 rooms left.",
    includes: [
      "Breakfast & lunch included (Half Board)",
      "2 single beds (extra long, > 2 metres)",
      "Free toiletries",
      "Clothes rack",
      "Dining area",
      "Balcony",
      "Garden view",
    ],
    includes2: [
      "Pool view",
      "Mountain view",
      "Free WiFi in public areas",
      "Free private parking (reservation needed)",
      "Coffee machine",
      "Tea/Coffee maker",
      "Daily housekeeping",
    ],
    features: [
      { icon: "🎨", title: "Evening Entertainment", desc: "Entertainment staff on site" },
      { icon: "📚", title: "Tour Desk", desc: "Guided tours arranged" },
      { icon: "🍵", title: "Breakfast in Room", desc: "In-room breakfast available" },
      { icon: "🧘", title: "Kids Club", desc: "Indoor play area for children" },
      { icon: "🌿", title: "Garden & Terrace", desc: "Outdoor garden and terrace" },
      { icon: "🎵", title: "Outdoor Pool", desc: "Free outdoor pool with water slide" },
    ],
    amenities: [
      { title: "Breakfast & Lunch Included", icon: "🍽️" },
      { title: "Extra Long Beds (> 2 metres)", icon: "🛏️" },
      { title: "Outdoor Fireplace", icon: "🔥" },
      { title: "Balcony with Views", icon: "🌄" },
      { title: "Free Toiletries", icon: "🧴" },
      { title: "Coffee Machine", icon: "☕" },
    ],
    services: [
      { title: "Outdoor Swimming Pool", img: "https://safar.devsvibe.co/wp-content/uploads/2025/10/accommodation-services-5.png" },
      { title: "Wellness Studio", img: "https://safar.devsvibe.co/wp-content/uploads/2025/10/accommodation-services-4.png" },
      { title: "Restaurant & Bar", img: "https://safar.devsvibe.co/wp-content/uploads/2025/10/accommodation-services-6.png" },
      { title: "24hr Security", img: "https://safar.devsvibe.co/wp-content/uploads/2025/10/accommodation-services-3.png" },
      { title: "Free WiFi", img: "https://safar.devsvibe.co/wp-content/uploads/2025/10/accommodation-services-2.png" },
      { title: "Valet Service", img: "https://safar.devsvibe.co/wp-content/uploads/2025/10/accommodation-services-1.png" },
    ],
    details: { guests: 2, view: "Garden / Pool / Mountain View", size: "20m²", bedType: "2 Single Beds", category: "Deluxe Half Board", bedrooms: 1, bathrooms: 1, location: "On-site" },
    rating: { overall: 4.4, total: 2 },
    ratingBreakdown: [
      { label: "AMENITIES", value: 4.5 },
      { label: "ENVIRONMENT", value: 4.8 },
      { label: "LOCATIONS", value: 4.0 },
      { label: "PRICE", value: 4.5 },
      { label: "ROOMS", value: 4.5 },
      { label: "SERVICES", value: 4.0 },
    ],
    reviews: [
      { name: "Sofia Reyes", date: "January 3, 2026", rating: 4.5, text: "Incredible experience with meals included. The half-board option made everything so convenient — truly one-of-a-kind value." },
    ],
    tags: ["Half Board", "Breakfast Included", "Lunch Included", "Balcony", "Mountain View", "Free Cancellation", "No Credit Card"],
    lat: 34.0449, lng: -118.2607,
  },
];